-- =============================================================================
-- Migration 001: Crear tablas del sistema de Traslados Comerciales
-- Ejecutar en el SQL Editor de Supabase (una sola vez, en orden)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. traslados_despachos — Cabecera del despacho
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS traslados_despachos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origen          VARCHAR(20)    NOT NULL DEFAULT 'PV001',
  destino         VARCHAR(20)    NOT NULL,
  despachador_id  VARCHAR(100),
  admin_id        VARCHAR(100),
  criterios       JSONB,
  estado          VARCHAR(30)    NOT NULL DEFAULT 'Creado',
  created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Índices para filtros comunes
CREATE INDEX IF NOT EXISTS idx_despachos_estado        ON traslados_despachos(estado);
CREATE INDEX IF NOT EXISTS idx_despachos_despachador    ON traslados_despachos(despachador_id);
CREATE INDEX IF NOT EXISTS idx_despachos_admin          ON traslados_despachos(admin_id);
CREATE INDEX IF NOT EXISTS idx_despachos_created_at     ON traslados_despachos(created_at DESC);

-- ---------------------------------------------------------------------------
-- 2. traslados_items — Productos incluidos en un despacho
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS traslados_items (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  despacho_id           BIGINT          NOT NULL REFERENCES traslados_despachos(id) ON DELETE CASCADE,
  codigo_item           VARCHAR(20)     NOT NULL,
  descripcion           TEXT,
  unidad_medida         VARCHAR(10),
  sugerido              NUMERIC(12,2),
  cantidad_admin        NUMERIC(12,2)   NOT NULL DEFAULT 0,
  cantidad_despachador  NUMERIC(12,2),
  cantidad_auditor      NUMERIC(12,2),
  diferencia            NUMERIC(12,2),
  aceptado              BOOLEAN,
  created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- Índices para joins y búsquedas
CREATE INDEX IF NOT EXISTS idx_items_despacho_id ON traslados_items(despacho_id);
CREATE INDEX IF NOT EXISTS idx_items_codigo      ON traslados_items(codigo_item);

-- ---------------------------------------------------------------------------
-- 3. traslados_firmas — Firmas digitales (despachador y auditor)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS traslados_firmas (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  despacho_id BIGINT        NOT NULL REFERENCES traslados_despachos(id) ON DELETE CASCADE,
  rol         VARCHAR(30)   NOT NULL,  -- 'despachador' | 'auditor'
  firma_data  TEXT          NOT NULL,  -- base64 de la firma
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_firmas_despacho_id ON traslados_firmas(despacho_id);

-- ---------------------------------------------------------------------------
-- Trigger: actualizar updated_at automáticamente
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_despachos'
  ) THEN
    CREATE TRIGGER set_updated_at_despachos
      BEFORE UPDATE ON traslados_despachos
      FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_items'
  ) THEN
    CREATE TRIGGER set_updated_at_items
      BEFORE UPDATE ON traslados_items
      FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- RLS: Deshabilitado porque usamos service_role desde el backend
-- (si en el futuro se quiere RLS, habilitar con políticas por rol)
-- ---------------------------------------------------------------------------
ALTER TABLE traslados_despachos DISABLE ROW LEVEL SECURITY;
ALTER TABLE traslados_items     DISABLE ROW LEVEL SECURITY;
ALTER TABLE traslados_firmas    DISABLE ROW LEVEL SECURITY;
